[template.environment]
  GQL_HOST = "https://shop.atl5d.com/graphql"
  NUXT_IMAGE_DOMAINS = "atl5d.com"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.shop.atl5d.com/.*"]
